#!/bin/bash

echo "=== Replacing lucide-react imports with react-icons ==="

# Files to update
files=(
  "src/components/mobile/BottomSheet.tsx"
  "src/components/mobile/MobileBottomNav.tsx"
  "src/components/mobile/MobileEscrowCreation.tsx"
  "src/components/mobile/escrow/MobileEscrowStepMilestones.tsx"
  "src/components/mobile/escrow/MobileEscrowStepKOL.tsx"
  "src/components/mobile/escrow/MobileEscrowStepBasic.tsx"
  "src/components/mobile/MobileTokenPage.tsx"
  "src/components/mobile/MobileHomepageV2.tsx"
  "src/components/mobile/MobileTokenCreation.tsx"
  "src/components/mobile/MobileVerifierPage.tsx"
  "src/components/mobile/MobileEscrowDashboard.tsx"
  "src/components/mobile/MobileAdminPage.tsx"
  "src/components/mobile/MobileBrowsePage.tsx"
  "src/components/mobile/MobileFullMenu.tsx"
  "src/components/ErrorBoundary.tsx"
  "src/app/escrow/docs/page.tsx"
  "src/app/portfolio/page.tsx"
  "src/app/token/new/page.tsx"
  "src/components/alien/Layout.tsx"
  "src/components/alien/NotificationModal.tsx"
  "src/components/alien/SettingsModal.tsx"
)

# Common icon mappings from lucide-react to react-icons/fi
declare -A icon_map=(
  ["ChevronLeft"]="FiChevronLeft"
  ["ChevronRight"]="FiChevronRight"
  ["ChevronDown"]="FiChevronDown"
  ["ChevronUp"]="FiChevronUp"
  ["X"]="FiX"
  ["Plus"]="FiPlus"
  ["Minus"]="FiMinus"
  ["Search"]="FiSearch"
  ["Filter"]="FiFilter"
  ["Settings"]="FiSettings"
  ["User"]="FiUser"
  ["Users"]="FiUsers"
  ["Home"]="FiHome"
  ["DollarSign"]="FiDollarSign"
  ["TrendingUp"]="FiTrendingUp"
  ["TrendingDown"]="FiTrendingDown"
  ["Shield"]="FiShield"
  ["Lock"]="FiLock"
  ["Unlock"]="FiUnlock"
  ["Eye"]="FiEye"
  ["EyeOff"]="FiEyeOff"
  ["Copy"]="FiCopy"
  ["Check"]="FiCheck"
  ["CheckCircle"]="FiCheckCircle"
  ["AlertCircle"]="FiAlertCircle"
  ["Info"]="FiInfo"
  ["Globe"]="FiGlobe"
  ["Mail"]="FiMail"
  ["Phone"]="FiPhone"
  ["Calendar"]="FiCalendar"
  ["Clock"]="FiClock"
  ["Download"]="FiDownload"
  ["Upload"]="FiUpload"
  ["File"]="FiFile"
  ["FileText"]="FiFileText"
  ["Folder"]="FiFolder"
  ["Edit"]="FiEdit2"
  ["Edit2"]="FiEdit2"
  ["Edit3"]="FiEdit3"
  ["Trash"]="FiTrash2"
  ["Trash2"]="FiTrash2"
  ["Save"]="FiSave"
  ["Send"]="FiSend"
  ["Share"]="FiShare2"
  ["Share2"]="FiShare2"
  ["Link"]="FiLink"
  ["ExternalLink"]="FiExternalLink"
  ["Menu"]="FiMenu"
  ["Grid"]="FiGrid"
  ["List"]="FiList"
  ["Heart"]="FiHeart"
  ["Star"]="FiStar"
  ["Bell"]="FiBell"
  ["BellOff"]="FiBellOff"
  ["Camera"]="FiCamera"
  ["Image"]="FiImage"
  ["Play"]="FiPlay"
  ["Pause"]="FiPause"
  ["MoreVertical"]="FiMoreVertical"
  ["MoreHorizontal"]="FiMoreHorizontal"
  ["ArrowUp"]="FiArrowUp"
  ["ArrowDown"]="FiArrowDown"
  ["ArrowLeft"]="FiArrowLeft"
  ["ArrowRight"]="FiArrowRight"
  ["ArrowUpRight"]="FiArrowUpRight"
  ["ArrowDownRight"]="FiArrowDownRight"
  ["RefreshCw"]="FiRefreshCw"
  ["RotateCw"]="FiRotateCw"
  ["Zap"]="FiZap"
  ["Activity"]="FiActivity"
  ["Award"]="FiAward"
  ["Target"]="FiTarget"
  ["Gift"]="FiGift"
  ["CreditCard"]="FiCreditCard"
  ["BookOpen"]="FiBookOpen"
  ["Code"]="FiCode"
  ["MessageCircle"]="FiMessageCircle"
  ["MessageSquare"]="FiMessageSquare"
  ["Briefcase"]="FiBriefcase"
  ["Package"]="FiPackage"
  ["Box"]="FiBox"
  ["AlertTriangle"]="FiAlertTriangle"
  ["HelpCircle"]="FiHelpCircle"
  ["LogIn"]="FiLogIn"
  ["LogOut"]="FiLogOut"
  ["Wallet"]="FiDollarSign"
  ["Trophy"]="FiAward"
  ["Layers"]="FiLayers"
  ["Monitor"]="FiMonitor"
  ["Database"]="FiDatabase"
  ["Server"]="FiServer"
  ["Cloud"]="FiCloud"
  ["Cpu"]="FiCpu"
  ["Layout"]="FiLayout"
  ["Sliders"]="FiSliders"
  ["BarChart"]="FiBarChart"
  ["BarChart2"]="FiBarChart2"
  ["PieChart"]="FiPieChart"
  ["LineChart"]="FiActivity"
  ["Twitter"]="FiTwitter"
  ["Facebook"]="FiFacebook"
  ["Instagram"]="FiInstagram"
  ["Github"]="FiGithub"
  ["Linkedin"]="FiLinkedin"
  ["Youtube"]="FiYoutube"
)

for file in "${files[@]}"; do
  if [ -f "$file" ]; then
    echo "Processing $file..."
    
    # First, replace the import statement
    sed -i "s/from 'lucide-react'/from 'react-icons\/fi'/g" "$file"
    
    # Then replace each icon name
    for old_icon in "${!icon_map[@]}"; do
      new_icon="${icon_map[$old_icon]}"
      # Replace in imports
      sed -i "s/\b${old_icon}\b/${new_icon}/g" "$file"
    done
    
    echo "  ✓ Updated $file"
  else
    echo "  ⚠ File not found: $file"
  fi
done

echo "=== Lucide to react-icons conversion complete ==="